[package]
name = "zmx_dll_test"
version = "0.1.0"
edition = "2021"

[lib] # create a C-compatible dynamic library, as opposed to Rust "dylib"
crate-type = ["cdylib"]

[dependencies]
bincode = "2.0.0-rc.3"
winapi = { version = "0.3.9", features = ["winnt"] }
